export const translations = {
    es: {
        nav: { overview: "Resumen", statistics: "Estadísticas", claims: "Siniestros", customers: "Clientes", analytics: "Diagnóstico", settings: "Configuración", history: "Historial" },
        summary: { cost: "Costo Total", records: "Registros", risk: "Siniestralidad", efficiency: "Eficiencia", analyzed: "Analizado", rows: "Filas", kpi: "KPI", high: "Alta" },
        overview: { title: "Análisis Comparativo", subtitle: "Comparación de Costos Promedio por Marca.", anomalies_title: "Anomalías y Datos", expensive_brand: "Marca Costosa", frequent_brand: "Más Frecuente", tip: "Tip:", tip_desc: "Pasa el cursor sobre los puntos para ver detalles.", no_anomalies: "No se encontraron anomalías.", unknown: "Desc.", na: "N/A" },
        statistics: { title: "Costos por Marca", retention_dist: "Distribución de Retención", cost_dist: "Distribución de Costos", no_data: "No hay datos", temporal_trends: "Tendencias Temporales", no_temporal_data: "No hay datos temporales", frequency_heatmap: "Frecuencia por Marca y Mes", no_heatmap_data: "No hay datos para heatmap" },
        claims: { title: "Desglose de Datos", categories: "Categorías", brand: "Marca", claims: "Siniestros", avg_cost: "Costo Avg", retention: "Retención", frequent_model: "Modelo Frecuente", estimated_repair: "Reparación est.", no_anomalies_detected: "No se detectaron anomalías." },
        customers: { retention_detected: "Retención Detectada", max_cost: "Costo Máximo", max_value_detected: "Valor más alto detectado." },
        analytics: { title: "Anomalías", subtitle: "Valores fuera de rango", summary_title: "Resumen del Archivo", structure: "Estructura", distribution: "Distribución", structure_desc: (rows: number, groups: number) => `Se analizaron ${rows} filas. Se identificaron ${groups} grupos únicos (marcas/modelos).`, distribution_desc: (avg: string) => `El costo promedio global es de €${avg}.` },
        settings: { title: "Configuración", subtitle: "Personaliza tu experiencia.", language: "Idioma", theme: "Tema", dark: "Oscuro", light: "Claro", auto: "Automático", blue: "Azul", purple: "Púrpura", green: "Verde", highContrastLight: "Alto Contraste (Claro)", highContrastDark: "Alto Contraste (Oscuro)", privateMode: "Modo Privado", privateModeDesc: "No guardar historial de archivos" },
        history: { title: "Historial de Archivos", empty: "No hay archivos en el historial", records: "Registros", total_cost: "Costo Total", size: "Tamaño", load: "Cargar análisis", clear_all: "Limpiar todo" },
        upload: { title: "Cargar Datos", subtitle: "Arrastra tu CSV, JSON o TXT. Análisis automático de costos y marcas.", button: "Seleccionar Archivo" },
        status: { analyzing: "Analizando...", patterns: "Identificando patrones", error_title: "Error en el análisis", error_desc: "No se pudieron extraer datos válidos.", retry: "Reintentar", file: "Archivo" },
        anomalies: { highPrice: (avg: string) => `Precio muy superior al promedio (€${avg})` },
        dashboard: { edit_mode: "Modo Edición", view_mode: "Modo Vista", configure: "Configurar Dashboard", configure_title: "Configurar Dashboard", layout_name: "Nombre del Layout", current_widgets: "Widgets Actuales", add_widgets: "Añadir Widgets", saved_layouts: "Layouts Guardados", no_saved_layouts: "No hay layouts guardados", load: "Cargar", cancel: "Cancelar", save: "Guardar Configuración", placeholder: "Mi Dashboard Personalizado", general_summary: "Resumen General", brand_comparison: "Comparación de Marcas", cost_distribution: "Distribución de Costos", retention: "Retención", temporal_trends: "Tendencias Temporales", frequency_heatmap: "Frecuencia por Marca y Mes", metrics_table: "Tabla de Métricas", anomalies: "Anomalías" }
    },
    en: {
        nav: { overview: "Overview", statistics: "Statistics", claims: "Claims", customers: "Customers", analytics: "Diagnostics", settings: "Settings", history: "History" },
        summary: { cost: "Total Cost", records: "Records", risk: "Claim Ratio", efficiency: "Efficiency", analyzed: "Analyzed", rows: "Rows", kpi: "KPI", high: "High" },
        overview: { title: "Comparative Analysis", subtitle: "Average Cost Comparison by Brand.", anomalies_title: "Anomalies & Data", expensive_brand: "Expensive Brand", frequent_brand: "Most Frequent", tip: "Tip:", tip_desc: "Hover over points for details.", no_anomalies: "No anomalies found.", unknown: "Unk.", na: "N/A" },
        statistics: { title: "Costs by Brand", retention_dist: "Retention Distribution", cost_dist: "Cost Distribution", no_data: "No data", temporal_trends: "Temporal Trends", no_temporal_data: "No temporal data", frequency_heatmap: "Frequency by Brand and Month", no_heatmap_data: "No data for heatmap" },
        claims: { title: "Data Breakdown", categories: "Categories", brand: "Brand", claims: "Claims", avg_cost: "Avg Cost", retention: "Retention", frequent_model: "Frequent Model", estimated_repair: "Est. Repair", no_anomalies_detected: "No anomalies detected." },
        customers: { retention_detected: "Retention Detected", max_cost: "Max Cost", max_value_detected: "Highest value detected." },
        analytics: { title: "Anomalies", subtitle: "Values out of range", summary_title: "File Summary", structure: "Structure", distribution: "Distribution", structure_desc: (rows: number, groups: number) => `Analyzed ${rows} rows. Identified ${groups} unique groups (brands/models).`, distribution_desc: (avg: string) => `Global average cost is €${avg}.` },
        settings: { title: "Settings", subtitle: "Customize your experience.", language: "Language", theme: "Theme", dark: "Dark", light: "Light", auto: "Auto", blue: "Blue", purple: "Purple", green: "Green", highContrastLight: "High Contrast (Light)", highContrastDark: "High Contrast (Dark)", privateMode: "Private Mode", privateModeDesc: "Don't save file history" },
        history: { title: "File History", empty: "No files in history", records: "Records", total_cost: "Total Cost", size: "Size", load: "Load analysis", clear_all: "Clear all" },
        upload: { title: "Upload Data", subtitle: "Drag your CSV, JSON or TXT. Auto analysis of costs and brands.", button: "Select File" },
        status: { analyzing: "Analyzing...", patterns: "Identifying patterns", error_title: "Analysis Error", error_desc: "Could not extract valid data.", retry: "Retry", file: "File" },
        anomalies: { highPrice: (avg: string) => `Price significantly above average (€${avg})` },
        dashboard: { edit_mode: "Edit Mode", view_mode: "View Mode", configure: "Configure Dashboard", configure_title: "Configure Dashboard", layout_name: "Layout Name", current_widgets: "Current Widgets", add_widgets: "Add Widgets", saved_layouts: "Saved Layouts", no_saved_layouts: "No saved layouts", load: "Load", cancel: "Cancel", save: "Save Configuration", placeholder: "My Custom Dashboard", general_summary: "General Summary", brand_comparison: "Brand Comparison", cost_distribution: "Cost Distribution", retention: "Retention", temporal_trends: "Temporal Trends", frequency_heatmap: "Frequency by Brand and Month", metrics_table: "Metrics Table", anomalies: "Anomalies" }
    },
    de: {
        nav: { overview: "Übersicht", statistics: "Statistik", claims: "Schäden", customers: "Kunden", analytics: "Diagnose", settings: "Einstellungen", history: "Verlauf" },
        summary: { cost: "Gesamtkosten", records: "Datensätze", risk: "Schadenquote", efficiency: "Effizienz", analyzed: "Analysiert", rows: "Zeilen", kpi: "KPI", high: "Hoch" },
        overview: { title: "Vergleichsanalyse", subtitle: "Durchschnittskostenvergleich nach Marke.", anomalies_title: "Anomalien & Daten", expensive_brand: "Teure Marke", frequent_brand: "Häufigste", tip: "Tipp:", tip_desc: "Fahren Sie über die Punkte für Details.", no_anomalies: "Keine Anomalien gefunden.", unknown: "Unbek.", na: "N/V" },
        statistics: { title: "Kosten nach Marke", retention_dist: "Verbleibsverteilung", cost_dist: "Kostenverteilung", no_data: "Keine Daten", temporal_trends: "Zeitliche Trends", no_temporal_data: "Keine zeitlichen Daten", frequency_heatmap: "Häufigkeit nach Marke und Monat", no_heatmap_data: "Keine Daten für Heatmap" },
        claims: { title: "Datenaufschlüsselung", categories: "Kategorien", brand: "Marke", claims: "Schäden", avg_cost: "Ø Kosten", retention: "Bindung", frequent_model: "Häufiges Modell", estimated_repair: "Geschätzte Rep.", no_anomalies_detected: "Keine Anomalien erkannt." },
        customers: { retention_detected: "Erkannte Bindung", max_cost: "Max. Kosten", max_value_detected: "Höchster erkannter Wert." },
        analytics: { title: "Anomalien", subtitle: "Werte außerhalb des Bereichs", summary_title: "Dateizusammenfassung", structure: "Struktur", distribution: "Verteilung", structure_desc: (rows: number, groups: number) => `${rows} Zeilen analysiert. ${groups} einzigartige Gruppen (Marken/Modelle) identifiziert.`, distribution_desc: (avg: string) => `Der globale Durchschnittskostenwert beträgt €${avg}.` },
        settings: { title: "Einstellungen", subtitle: "Passen Sie Ihre Erfahrung an.", language: "Sprache", theme: "Thema", dark: "Dunkel", light: "Hell", auto: "Automatisch", blue: "Blau", purple: "Lila", green: "Grün", highContrastLight: "Hoher Kontrast (Hell)", highContrastDark: "Hoher Kontrast (Dunkel)", privateMode: "Privater Modus", privateModeDesc: "Kein Dateiverlauf speichern" },
        history: { title: "Dateiverlauf", empty: "Keine Dateien im Verlauf", records: "Datensätze", total_cost: "Gesamtkosten", size: "Größe", load: "Analyse laden", clear_all: "Alle löschen" },
        upload: { title: "Daten hochladen", subtitle: "Ziehen Sie Ihre CSV, JSON oder TXT. Auto-Analyse von Kosten und Marken.", button: "Datei auswählen" },
        status: { analyzing: "Analysieren...", patterns: "Muster erkennen", error_title: "Analysefehler", error_desc: "Konnte keine gültigen Daten extrahieren.", retry: "Wiederholen", file: "Datei" },
        anomalies: { highPrice: (avg: string) => `Preis deutlich über dem Durchschnitt (€${avg})` },
        dashboard: { edit_mode: "Bearbeitungsmodus", view_mode: "Ansichtsmodus", configure: "Dashboard Konfigurieren", configure_title: "Dashboard Konfigurieren", layout_name: "Layout-Name", current_widgets: "Aktuelle Widgets", add_widgets: "Widgets Hinzufügen", saved_layouts: "Gespeicherte Layouts", no_saved_layouts: "Keine gespeicherten Layouts", load: "Laden", cancel: "Abbrechen", save: "Konfiguration Speichern", placeholder: "Mein Benutzerdefiniertes Dashboard", general_summary: "Allgemeine Zusammenfassung", brand_comparison: "Markenvergleich", cost_distribution: "Kostenverteilung", retention: "Bindung", temporal_trends: "Zeitliche Trends", frequency_heatmap: "Häufigkeit nach Marke und Monat", metrics_table: "Metrik-Tabelle", anomalies: "Anomalien" }
    }
};
